######################################################################
# Automatically generated by qmake (3.0) Fri Sep 23 03:38:56 2016
######################################################################

TEMPLATE = app
TARGET = kvm-host-server
INCLUDEPATH += .
#INCLUDEPATH += /usr/src/linux-headers-4.7.3/include/
# Input
SOURCES += kvm-host-server.c
HEADERS += chardev.h \
    vm-memory.h \
    uuid-table.h \
    protocol.h \
    global-config.h \
    kernel-includes.h
